### PR TITLE
Added support for gz6 and jade

### PR DESCRIPTION
**Pull request by TheDash**

### CODE REVIEW

**Comment by oKermorgant** [comment]
Hi, 

Thanks for having added compatibility with gz6 and Jade. I am still working on Ubuntu 14.04 and Igloo so I cannot test the changes for now.

**Comment by TheDash** [comment]
Np. The Gazebo version used C++11x compiler so this just turns those flags on. I have other changes I will make later for project to make sure it works.

Thanks for this contribution, it has been a big help. Btw is this suppose to work for other robots? Perhaps you can help me with a simulation I am trying to do via email?

**Comment by oKermorgant** [comment]
It is designed to work with any other thruster-propelled robot, with or without an arm.
Just add the correspondings sections in the urdf so that the controller gets the transformation between the robot frame and the thruster forces. 
I can of course give a hand by email.

**Comment by TheDash** [comment]
Hi @oKermorgant 

I'm trying to map the thrusters with  6 thrusters bot robot no longer moves. Can you give me an example for how to map custom thrusters? E.g how does the rpy xyz work for it?

**Comment by oKermorgant** [comment]
Hi, 

An example is given in freefloating_gazebo_demo, in the g500.xacro file.
You have to specify the velocity transformation matrix of each thruster with regards to the robot origin.
For example the first thruster of the example reads :
<map>-1 0 0 0 0 ${-body_width/2}</map>

Meaning that is this thruster has 1m/s velocity, the robot will get -1 m/s on its X axis and a rotation around its Z axis.
All the maps are then concatenated in order to get the Jacobian between velocity space and thruster space.

**Pull request merged**
